# ============================================================================
# Project Atlas - ProGuard / R8 Configuration
# ============================================================================
# Aggressive size optimization for a lightweight virtual space application.
# Targets: Android 13+ (minSdk 33), ARM only (armeabi-v7a, arm64-v8a)
# ============================================================================

# ─── Aggressive Optimization ────────────────────────────────────────────────
# Maximize code shrinking and obfuscation for minimal APK size

-optimizationpasses 7
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-allowaccessmodification
-mergeinterfacesaggressively
-repackageclasses ''
-overloadaggressively

# ─── Keep Application Entry Points ──────────────────────────────────────────

-keep class com.atlas.virtualspace.AtlasApplication { *; }
-keep class com.atlas.virtualspace.ui.MainActivity { *; }

# ─── VirtualEngine Core Classes ─────────────────────────────────────────────
# These classes drive the virtual environment and must not be obfuscated
# because they are referenced via reflection by native code and IPC stubs.

-keep class com.atlas.virtualspace.core.engine.** { *; }
-keepclassmembers class com.atlas.virtualspace.core.engine.** { *; }

# ─── Hook Entry Points ─────────────────────────────────────────────────────
# Pine hook callbacks and Xposed-style entry points are discovered via
# reflection and must retain their exact names and signatures.

-keep class com.atlas.virtualspace.core.hook.** { *; }
-keepclassmembers class com.atlas.virtualspace.core.hook.** { *; }

# ─── IPC Stub Classes ──────────────────────────────────────────────────────
# Binder stubs, Parcelables, and AIDL-generated classes must be kept
# for cross-process communication to function correctly.

-keep class com.atlas.virtualspace.core.ipc.** { *; }
-keepclassmembers class com.atlas.virtualspace.core.ipc.** { *; }
-keep class * extends android.os.Binder { *; }
-keep class * implements android.os.Parcelable {
    public static final ** CREATOR;
}
-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

# ─── Pine Hooking Framework ────────────────────────────────────────────────
# Pine uses heavy reflection and JNI to intercept method calls.
# All public API and internal hook dispatch must be preserved.

-keep class top.canyie.pine.** { *; }
-keepclassmembers class top.canyie.pine.** { *; }
-keep class top.canyie.pine.xposed.** { *; }
-keepclassmembers class top.canyie.pine.xposed.** { *; }

# Pine callback interfaces — method names are resolved at runtime
-keepclassmembers interface top.canyie.pine.callback.** {
    *;
}

# ─── Shizuku ───────────────────────────────────────────────────────────────
# Shizuku uses AIDL-based IPC and annotation-driven permission checks.
# Provider and service stubs must remain intact.

-keep class dev.rikka.shizuku.** { *; }
-keepclassmembers class dev.rikka.shizuku.** { *; }
-keep class * extends dev.rikka.shizuku.server.ShizukuService { *; }

# Shizuku's hidden API stubs
-keep class dev.rikka.hidden.** { *; }

# ─── Native Methods ────────────────────────────────────────────────────────
# All JNI native method names must be preserved for correct symbol resolution.

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

# ─── AndroidX ──────────────────────────────────────────────────────────────

# Core
-keep class androidx.core.** { *; }
-dontwarn androidx.core.**

# Activity & Fragment
-keep class * extends androidx.activity.ComponentActivity { *; }
-keep class * extends androidx.fragment.app.Fragment { *; }

# Lifecycle
-keep class * extends androidx.lifecycle.ViewModel { <init>(...); }
-keep class * implements androidx.lifecycle.ViewModelProvider$Factory {
    <init>(...);
}
-keepclassmembers class androidx.lifecycle.** { *; }

# SavedState
-keep class * implements androidx.savedstate.SavedStateRegistry$SavedStateProvider { *; }

# ─── Jetpack Compose ───────────────────────────────────────────────────────
# Compose uses compiler-generated code with specific naming conventions.
# Runtime and compiler plugin internals must be preserved.

-dontwarn androidx.compose.**
-keep class androidx.compose.runtime.** { *; }
-keepclassmembers class androidx.compose.runtime.** { *; }

# Compose modifier & composable function signatures
-keepclassmembers class * {
    *** *(***);
}

# Compose Stubs (generated by the Compose compiler plugin)
-keep class **.ComposableSingletons$* { *; }
-keepclassmembers class **.ComposableSingletons$* { *; }

# ─── Kotlin & Coroutines ───────────────────────────────────────────────────

-dontwarn kotlinx.coroutines.**

# Kotlin metadata — needed for reflection-based frameworks
-keepattributes RuntimeVisibleAnnotations
-keep class kotlin.Metadata { *; }
-keepclassmembers class kotlin.Metadata { *; }

# Kotlin coroutines — keep state machine internals
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepclassmembers class kotlinx.coroutines.** {
    volatile ** _state;
    ** _label;
}

# Ensure coroutine context elements are not stripped
-keep class kotlinx.coroutines.android.** { *; }
-keepclassmembers class kotlinx.coroutines.android.** { *; }

# Kotlin stdlib
-dontwarn kotlin.**
-keep class kotlin.** { *; }
-keepclassmembers class kotlin.** { *; }
-keepclassmembers class * {
    ** Companion;
}

# Kotlin extension function resolution
-keepclassmembers class **$WhenMappings {
    <fields>;
}

# ─── Room Database ─────────────────────────────────────────────────────────
# Room uses annotation processing to generate DAO implementations.
# Entity classes, DAO interfaces, and Database classes must be preserved.

# Room entities — all fields must be accessible for column mapping
-keep class * extends androidx.room.Entity { *; }
-keepclassmembers class * extends androidx.room.Entity { *; }

# Keep all classes annotated with @Entity
-keep @androidx.room.Entity class * { *; }

# Room DAOs — generated implementations reference interface method signatures
-keep interface * extends androidx.room.Dao { *; }
-keepclassmembers interface * extends androidx.room.Dao { *; }

# Room Database — the generated impl class is loaded by reflection
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Database class * { *; }

# Room TypeConverters
-keep class * extends androidx.room.TypeConverter { *; }
-keepclassmembers class * {
    @androidx.room.TypeConverter *;
}

# Embedded entities
-keepclassmembers class * {
    @androidx.room.Embedded *;
    @androidx.room.Relation *;
}

# ─── Hilt / Dagger ─────────────────────────────────────────────────────────
# Hilt generates code at compile time but uses reflection for component
# discovery and member injection in framework classes.

# Hilt application & entry points
-keep class * extends dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper { *; }
-keep @dagger.hilt.android.lifecycle.HiltViewModel class * { *; }
-keep @dagger.hilt.android.AndroidEntryPoint class * { *; }

# Hilt generated components
-keep class **_HiltModules* { *; }
-keep class **_HiltComponents* { *; }
-keep class **_GeneratedInjector { *; }
-keep class **_Factory { *; }
-keep class **_MembersInjector { *; }

# Dagger core
-dontwarn dagger.**
-keep class dagger.** { *; }
-keepclassmembers class dagger.** { *; }
-keep class * implements dagger.hilt.android.internal.managers.ComponentSupplier { *; }

# javax.inject
-dontwarn javax.inject.**
-keep class javax.inject.** { *; }

# Hilt's ViewModelFactory
-keepclassmembers class * extends androidx.lifecycle.ViewModel {
    <init>(javax.inject.Provider<java.util.Map<java.lang.String, javax.inject.Provider<androidx.lifecycle.ViewModel>>>);
    <init>(java.util.Map<java.lang.String, javax.inject.Provider<androidx.lifecycle.ViewModel>>);
}

# ─── Gson ───────────────────────────────────────────────────────────────────
# Gson uses reflection to serialize/deserialize objects. Keep model classes
# and type adapters that are used for IPC data transfer and config storage.

# Keep Gson TypeToken and TypeAdapter subclasses
-keep class * extends com.google.gson.TypeAdapter { *; }
-keep class * implements com.google.gson.TypeAdapterFactory { *; }
-keep class * extends com.google.gson.TypeToken { *; }
-keep class * implements com.google.gson.JsonSerializer { *; }
-keep class * implements com.google.gson.JsonDeserializer { *; }

# Gson @SerializedName annotated fields
-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
}

# Keep all model/data classes used with Gson (convention: *.model.**)
-keep class com.atlas.virtualspace.data.model.** { *; }
-keepclassmembers class com.atlas.virtualspace.data.model.** { *; }

# Gson internal
-keep class com.google.gson.** { *; }
-keepclassmembers class com.google.gson.** { *; }
-dontwarn sun.misc.**
-dontwarn com.google.gson.**

# ─── Timber (Logging) ──────────────────────────────────────────────────────

-keep class timber.log.Timber { *; }
-keep class timber.log.Timber$Tree { *; }

# ─── Remove Logging in Release ─────────────────────────────────────────────
# Strip all logging calls to reduce APK size and prevent information leakage.
# Timber trees are planted conditionally; remove debug tree in release.

-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int d(...);
    public static int i(...);
}

# Also strip Timber.d and Timber.v — they are no-ops in release when
# no debug tree is planted, but removing the call sites shrinks code further.
-assumenosideeffects class timber.log.Timber {
    public static *** v(...);
    public static *** d(...);
}

# ─── APK Parsing ───────────────────────────────────────────────────────────

-keep class net.dongliu.apk.parser.** { *; }
-keepclassmembers class net.dongliu.apk.parser.** { *; }
-dontwarn net.dongliu.apk.parser.**

# ─── Apache Commons Compress ───────────────────────────────────────────────

-dontwarn org.apache.commons.compress.**
-keep class org.apache.commons.compress.** { *; }

# ─── OkIO ───────────────────────────────────────────────────────────────────

-dontwarn okio.**
-keep class okio.** { *; }
-keep interface okio.** { *; }

# ─── Coil (Image Loading) ──────────────────────────────────────────────────

-dontwarn coil.**
-keep class coil.** { *; }

# ─── Accompanist ───────────────────────────────────────────────────────────

-dontwarn com.google.accompanist.**

# ─── File Provider ─────────────────────────────────────────────────────────

-keep class androidx.core.content.FileProvider { *; }

# ─── Serializable Support ──────────────────────────────────────────────────
# Some IPC payloads implement Serializable for Bundle transport.

-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

-keepclassmembers class * implements java.io.Externalizable {
    public void writeExternal(java.io.ObjectOutput);
    public void readExternal(java.io.ObjectInput);
}

# ─── Enum Support ──────────────────────────────────────────────────────────

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# ─── R Classes ─────────────────────────────────────────────────────────────

-keepclassmembers class **.R$* {
    public static <fields>;
}

# ─── Annotation-Based Keep Rules ───────────────────────────────────────────
# Respect standard Android keep annotations

-keepattributes *Annotation*
-keepattributes Signature
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes EnclosingMethod

# Classes annotated with @Keep
-keep @androidx.annotation.Keep class * { *; }
-keepclassmembers class * {
    @androidx.annotation.Keep *;
}

# ─── Service Loader ────────────────────────────────────────────────────────

-keep class META-INF.services.** { *; }

# ─── General Warnings Suppression ──────────────────────────────────────────

-dontwarn javax.annotation.**
-dontwarn org.codehaus.**
-dontwarn java.lang.invoke.StringConcatFactory
-dontwarn java.lang.invoke.VarHandle

# ─── Custom Application Classes ────────────────────────────────────────────
# Hilt's generated application component requires specific class retention

-keep class com.atlas.virtualspace.AtlasApplication_GeneratedInjector { *; }
-keep class **_HiltModules** { *; }
-keep class **_HiltComponents** { *; }
-keep class **_SingletonC** { *; }

# ─── Reflection-Loaded Framework Classes ───────────────────────────────────
# These are loaded by class name strings in the virtual engine;

-keep class com.atlas.virtualspace.core.VirtualSpaceManager { *; }
-keep class com.atlas.virtualspace.core.config.VirtualSpaceConfig { *; }
-keep class com.atlas.virtualspace.core.config.** { *; }

# ─── WorkManager (if added later) ──────────────────────────────────────────

-keep class androidx.work.** { *; }
-dontwarn androidx.work.**

# ─── Splash Screen ─────────────────────────────────────────────────────────

-keep class androidx.core.splashscreen.** { *; }
-dontwarn androidx.core.splashscreen.**

# ─── Boot Receiver ─────────────────────────────────────────────────────────

-keep class com.atlas.virtualspace.receiver.** { *; }
